### ISSUE TITLE
Edit on GitHub link 404

### ISSUE THREAD

**Issue by mirestrepo** [bcbi/PredictMD.jl#140]
On the docs, the edit on GitHub link is broken

**Comment by DilumAluthge** [comment]
Interesting. This is complicated because for many of the files, the ".md" file is dynamically generated by Literate.jl - and thus is not checked in to version control. I think the easiest thing to do for now is to remove the "edit on github" link entirely.

**Comment by DilumAluthge** [comment]
The harder thing is for "make_docs.jl" to go in and edit each of those links to point to the correct place.
