### ISSUE TITLE
Update Stronghold documentation 

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/PredictMD.jl#318]

**Comment by mcmcgrath13** [comment]
@DilumAluthge Stronghold documentation/references generally should not be in a public repository - it is a secure computing environment that is not available to the public.

**Comment by DilumAluthge** [comment]
Sounds good. Where should I host Stronghold-specific documentation for PredictMD.

Dilum Aluthge
Web: https://aluthge.com
Email: dilum@aluthge.com
