### ISSUE TITLE
Loading models without pre-defining them

### ISSUE THREAD

**Issue by mirestrepo** [bcbi/PredictMD.jl#84]
Loading models requires predefining the values and functions that construct them. Ideally the loader should do that. Serialization may not be possible in some cases but we should look into this

**Comment by DilumAluthge** [comment]
Also take a look here - https://github.com/denizyuret/Knet.jl/blob/master/examples/dl-tutorial/mlp.ipynb (see input cell 30). They use JLD to save the models to file, but they only save the weights (as well as the current training loss, testing loss, etc). They don't serialize the predict function ( ```multilinear(w,x)``` in this example).

**Comment by DilumAluthge** [comment]
One last thought: I've been playing around with BSON.jl (https://github.com/MikeInnes/BSON.jl), and it seems that BSON.jl supports saving functions to file. So this may be an easy way to solve this issue.

**Comment by DilumAluthge** [comment]
Fixed in develop. You can load models without predefining them. The one exception is Knet models - you have to define predict() and loss() before loading the model.
